/* SciMetricsPro — bilingual glossary for preparing a literature search (Import · Keywords).
   Each entry: [type, Spanish forms, English forms], forms separated by commas; the first English form is the one
   used to compose phrases. Plurals and the gender of adjectives are matched automatically.
   Types: n = concept, a = modifier (goes before the noun in English), o = organism (common and scientific names),
          p = place, g = generic research word (dropped when it stands alone: effect, analysis, study…). */
'use strict';

window.SMP_GLOSSARY = [
  /* ---------- generic research words ---------- */
  ['g', 'efecto, efectos', 'effect, effects'],
  ['g', 'influencia', 'influence'],
  ['g', 'impacto', 'impact'],
  ['g', 'evaluación, evaluar, valoración', 'evaluation, assessment'],
  ['g', 'análisis, analizar', 'analysis'],
  ['g', 'estudio, estudiar, investigación', 'study, research'],
  ['g', 'caracterización, caracterizar', 'characterization, characterisation'],
  ['g', 'determinación, determinar', 'determination'],
  ['g', 'respuesta', 'response'],
  ['g', 'relación', 'relationship, relation'],
  ['g', 'papel, rol', 'role'],
  ['g', 'comparación, comparativo', 'comparison, comparative'],
  ['g', 'revisión, revisión sistemática, revisión de literatura, revisión bibliográfica', 'review, systematic review, literature review'],
  ['g', 'estado del arte, estado actual, situación actual', 'state of the art, current status'],
  ['g', 'perspectiva, perspectivas, avance, avances, tendencia, tendencias', 'perspectives, advances, trends'],
  ['g', 'análisis bibliométrico, bibliometría, bibliométrico', 'bibliometric analysis, bibliometrics'],
  ['g', 'enfoque, aproximación, propuesta', 'approach, proposal'],
  ['g', 'caso, estudio de caso', 'case, case study'],
  ['g', 'aplicación, uso, utilización, empleo', 'application, use, utilization'],
  ['g', 'factor, condición, nivel, tipo, parámetro, variable, aspecto', 'factor, condition, level, type, parameter, variable, aspect'],
  ['g', 'importancia, potencial, nuevo, novedoso, diferente, distinto, diverso, vario, alguno', 'importance, potential, new, novel, different, various, some'],
  ['g', 'región, zona, área, sitio, localidad', 'region, zone, area, site, locality'],
  ['g', 'método, metodología, técnica', 'method, methodology, technique'],
  ['g', 'sistema', 'system'],
  ['g', 'propiedad', 'property'],
  ['g', 'contenido', 'content'],
  ['g', 'identificación', 'identification'],

  /* ---------- general concepts ---------- */
  ['g', 'producción', 'production'],
  ['g', 'condiciones de campo, condición de campo', 'field conditions'],
  ['n', 'productividad', 'productivity'],
  ['n', 'rendimiento', 'yield, crop yield'],
  ['n', 'manejo, gestión', 'management'],
  ['n', 'tratamiento', 'treatment'],
  ['n', 'calidad', 'quality'],
  ['n', 'dosis', 'dose, rate'],
  ['n', 'indicador', 'indicator'],
  ['n', 'eficiencia', 'efficiency'],
  ['n', 'eficacia, efectividad', 'efficacy, effectiveness'],
  ['n', 'optimización', 'optimization, optimisation'],
  ['n', 'selección', 'selection'],
  ['n', 'detección', 'detection'],
  ['n', 'cuantificación', 'quantification'],
  ['n', 'predicción, pronóstico', 'prediction, forecasting'],
  ['n', 'estimación', 'estimation'],
  ['n', 'monitoreo, monitorización, seguimiento', 'monitoring'],
  ['n', 'mapeo, cartografía', 'mapping'],
  ['n', 'simulación', 'simulation'],
  ['n', 'modelo, modelación, modelado, modelización', 'model, modeling, modelling'],
  ['n', 'clasificación', 'classification'],
  ['n', 'distribución', 'distribution'],
  ['n', 'diversidad', 'diversity'],
  ['n', 'composición', 'composition'],
  ['n', 'estructura', 'structure'],
  ['n', 'dinámica', 'dynamics'],
  ['n', 'evolución', 'evolution'],
  ['n', 'variación, variabilidad', 'variation, variability'],
  ['n', 'desarrollo', 'development'],
  ['n', 'diagnóstico', 'diagnosis'],
  ['n', 'diseño', 'design'],
  ['n', 'prevalencia', 'prevalence'],
  ['n', 'incidencia', 'incidence'],
  ['n', 'severidad', 'severity'],
  ['n', 'conservación', 'conservation'],
  ['n', 'restauración', 'restoration'],
  ['n', 'sustentabilidad, sostenibilidad', 'sustainability'],
  ['n', 'adopción', 'adoption'],
  ['n', 'percepción', 'perception'],
  ['n', 'conocimiento', 'knowledge'],
  ['n', 'conocimiento tradicional, saberes tradicionales', 'traditional knowledge'],
  ['n', 'comunidad', 'community, communities'],
  ['n', 'productor, agricultor, campesino', 'farmers, producers, smallholders'],
  ['n', 'pequeño productor', 'smallholder farmers, smallholders'],
  ['n', 'política, política pública', 'policy, public policy'],
  ['n', 'economía', 'economics, economy'],
  ['n', 'rentabilidad', 'profitability'],
  ['n', 'costo, coste', 'cost'],
  ['n', 'mercado, comercialización', 'market, marketing, commercialization'],
  ['n', 'cadena de valor', 'value chain'],
  ['n', 'seguridad alimentaria', 'food security'],
  ['n', 'soberanía alimentaria', 'food sovereignty'],
  ['n', 'pobreza', 'poverty'],
  ['n', 'educación', 'education'],
  ['n', 'enseñanza', 'teaching'],
  ['n', 'aprendizaje', 'learning'],
  ['n', 'estudiante', 'students'],
  ['n', 'docente, profesor', 'teachers'],
  ['n', 'universidad', 'university, higher education'],
  ['n', 'innovación', 'innovation'],
  ['n', 'tecnología', 'technology'],
  ['n', 'transferencia de tecnología', 'technology transfer'],
  ['n', 'extensión agrícola, extensionismo', 'agricultural extension'],

  /* ---------- modifiers ---------- */
  ['a', 'sustentable, sostenible', 'sustainable'],
  ['a', 'tradicional', 'traditional'],
  ['a', 'local', 'local'],
  ['a', 'rural', 'rural'],
  ['a', 'urbano', 'urban'],
  ['a', 'económico', 'economic'],
  ['a', 'social', 'social'],
  ['a', 'ambiental', 'environmental'],
  ['a', 'agrícola', 'agricultural'],
  ['a', 'agronómico', 'agronomic'],
  ['a', 'agroecológico', 'agroecological'],
  ['a', 'ecológico', 'ecological'],
  ['a', 'genético', 'genetic'],
  ['a', 'genómico', 'genomic'],
  ['a', 'molecular', 'molecular'],
  ['a', 'nutricional, nutrimental', 'nutritional'],
  ['a', 'vegetal', 'plant'],
  ['a', 'animal', 'animal'],
  ['a', 'forestal', 'forest'],
  ['a', 'tropical', 'tropical'],
  ['a', 'silvestre', 'wild'],
  ['a', 'nativo', 'native'],
  ['a', 'criollo', 'native, landrace'],
  ['a', 'comercial', 'commercial'],
  ['a', 'climático', 'climate'],
  ['a', 'hídrico', 'water'],
  ['a', 'salino', 'saline, salt'],
  ['a', 'térmico', 'thermal, heat'],
  ['a', 'biológico', 'biological'],
  ['a', 'químico, sintético', 'chemical, synthetic'],
  ['a', 'inorgánico', 'inorganic'],
  ['a', 'orgánico', 'organic'],
  ['a', 'mineral', 'mineral'],
  ['a', 'físico', 'physical'],
  ['a', 'fisicoquímico', 'physicochemical'],
  ['a', 'sensorial', 'sensory'],
  ['a', 'microbiano', 'microbial'],
  ['a', 'bacteriano', 'bacterial'],
  ['a', 'fúngico', 'fungal'],
  ['a', 'viral', 'viral'],
  ['a', 'integrado', 'integrated'],
  ['a', 'morfológico', 'morphological'],
  ['a', 'fisiológico', 'physiological'],
  ['a', 'bioquímico', 'biochemical'],
  ['a', 'fenotípico', 'phenotypic'],
  ['a', 'agroindustrial', 'agro-industrial'],
  ['a', 'hidropónico', 'hydroponic'],
  ['a', 'foliar', 'foliar'],
  ['a', 'edáfico', 'soil'],
  ['a', 'degradado', 'degraded'],
  ['a', 'contaminado', 'contaminated, polluted'],
  ['a', 'resistente', 'resistant'],
  ['a', 'tolerante', 'tolerant'],
  ['a', 'mejorado', 'improved'],
  ['a', 'híbrido', 'hybrid'],
  ['a', 'nitrogenado', 'nitrogen'],
  ['a', 'fosfatado, fosfórico', 'phosphorus, phosphate'],
  ['a', 'potásico', 'potassium, potash'],
  ['a', 'cálcico', 'calcium'],
  ['a', 'medicinal', 'medicinal'],
  ['a', 'funcional', 'functional'],
  ['a', 'antioxidante', 'antioxidant'],
  ['a', 'antimicrobiano', 'antimicrobial'],
  ['a', 'antibacteriano', 'antibacterial'],
  ['a', 'antifúngico', 'antifungal'],
  ['a', 'esencial', 'essential'],
  ['a', 'secundario', 'secondary'],

  /* ---------- plant production ---------- */
  ['n', 'agricultura', 'agriculture'],
  ['n', 'agricultura protegida', 'protected agriculture, protected cultivation, greenhouse production'],
  ['n', 'agricultura de conservación', 'conservation agriculture'],
  ['n', 'agricultura orgánica, agricultura ecológica', 'organic agriculture, organic farming'],
  ['n', 'agricultura de precisión', 'precision agriculture'],
  ['n', 'agricultura familiar', 'family farming'],
  ['n', 'agroecología', 'agroecology'],
  ['n', 'agroforestería, sistema agroforestal', 'agroforestry, agroforestry systems'],
  ['n', 'sistema de producción', 'production systems, farming systems'],
  ['n', 'milpa', 'milpa, maize-based polyculture'],
  ['n', 'policultivo, cultivo asociado, asociación de cultivos, cultivo intercalado', 'intercropping, polyculture'],
  ['n', 'rotación de cultivos', 'crop rotation'],
  ['n', 'labranza', 'tillage'],
  ['n', 'labranza de conservación, labranza cero, cero labranza', 'conservation tillage, no-tillage, zero tillage'],
  ['n', 'cultivo de cobertura', 'cover crops'],
  ['n', 'acolchado', 'mulching, mulch'],
  ['n', 'cultivo', 'crop, crops, cultivation'],
  ['n', 'hortaliza, verdura', 'vegetables, vegetable crops'],
  ['n', 'frutal, árbol frutal', 'fruit trees, fruit crops'],
  ['n', 'cereal', 'cereals'],
  ['n', 'leguminosa', 'legumes'],
  ['n', 'forraje', 'forage'],
  ['n', 'pasto, pastizal, pradera', 'grasses, grasslands, pastures'],
  ['n', 'planta ornamental, ornamental', 'ornamental plants'],
  ['n', 'planta medicinal', 'medicinal plants'],
  ['n', 'planta', 'plant, plants'],
  ['n', 'invernadero', 'greenhouse'],
  ['n', 'casa sombra, malla sombra', 'shade house, shade net'],
  ['n', 'campo abierto', 'open field'],
  ['n', 'riego', 'irrigation'],
  ['n', 'riego por goteo', 'drip irrigation'],
  ['n', 'agua', 'water'],
  ['n', 'uso eficiente del agua, eficiencia en el uso del agua', 'water use efficiency'],
  ['n', 'evapotranspiración', 'evapotranspiration'],
  ['n', 'fertilización, fertilizante, abonado', 'fertilization, fertilisation, fertilizer, fertiliser'],
  ['n', 'fertilización nitrogenada', 'nitrogen fertilization, nitrogen fertilisation, nitrogen fertilizer'],
  ['n', 'fertilización foliar, aplicación foliar', 'foliar fertilization, foliar application, foliar spray'],
  ['n', 'nutriente, nutrimento', 'nutrients'],
  ['n', 'macronutriente', 'macronutrients'],
  ['n', 'micronutriente', 'micronutrients'],
  ['n', 'nutrición', 'nutrition'],
  ['n', 'nutrición mineral', 'mineral nutrition, plant nutrition'],
  ['n', 'nutrición vegetal', 'plant nutrition'],
  ['n', 'absorción de nutrientes', 'nutrient uptake'],
  ['n', 'biofertilizante', 'biofertilizer, biofertiliser'],
  ['n', 'bioestimulante', 'biostimulant'],
  ['n', 'abono orgánico, enmienda orgánica', 'organic fertilizer, organic manure, organic amendment'],
  ['n', 'enmienda', 'amendment, soil amendment'],
  ['n', 'lodo residual, biosólido', 'sewage sludge, biosolids'],
  ['n', 'composta, compost', 'compost'],
  ['n', 'vermicomposta, lombricomposta', 'vermicompost'],
  ['n', 'estiércol', 'manure'],
  ['n', 'biocarbón, biochar', 'biochar'],
  ['n', 'nitrógeno', 'nitrogen'],
  ['n', 'fósforo', 'phosphorus'],
  ['n', 'potasio', 'potassium'],
  ['n', 'calcio', 'calcium'],
  ['n', 'magnesio', 'magnesium'],
  ['n', 'azufre', 'sulfur, sulphur'],
  ['n', 'hierro', 'iron'],
  ['n', 'zinc, cinc', 'zinc'],
  ['n', 'boro', 'boron'],
  ['n', 'manganeso', 'manganese'],
  ['n', 'cobre', 'copper'],
  ['n', 'silicio', 'silicon'],
  ['n', 'selenio', 'selenium'],
  ['n', 'metal pesado', 'heavy metals'],
  ['n', 'cadmio', 'cadmium'],
  ['n', 'plomo', 'lead'],
  ['n', 'arsénico', 'arsenic'],
  ['n', 'suelo', 'soil, soils'],
  ['n', 'fertilidad del suelo', 'soil fertility'],
  ['n', 'materia orgánica', 'organic matter, soil organic matter'],
  ['n', 'carbono orgánico', 'organic carbon, soil organic carbon'],
  ['n', 'erosión', 'erosion, soil erosion'],
  ['n', 'degradación del suelo', 'soil degradation, land degradation'],
  ['n', 'salud del suelo, calidad del suelo', 'soil health, soil quality'],
  ['n', 'microbiota, microbioma', 'microbiota, microbiome'],
  ['n', 'micorriza, hongo micorrízico', 'mycorrhiza, mycorrhizal fungi, arbuscular mycorrhizal fungi'],
  ['n', 'bacteria promotora del crecimiento vegetal, rizobacteria', 'plant growth-promoting bacteria, plant growth-promoting rhizobacteria, PGPR'],
  ['n', 'crecimiento', 'growth'],
  ['n', 'floración', 'flowering'],
  ['n', 'fructificación, amarre de fruto, cuajado', 'fruit set, fruiting'],
  ['n', 'polinización', 'pollination'],
  ['n', 'polinizador', 'pollinators'],
  ['n', 'germinación', 'germination'],
  ['n', 'semilla', 'seed, seeds'],
  ['n', 'calidad de semilla', 'seed quality'],
  ['n', 'plántula', 'seedlings'],
  ['n', 'vivero', 'nursery'],
  ['n', 'injerto, injertación', 'grafting, graft'],
  ['n', 'portainjerto, patrón', 'rootstock'],
  ['n', 'propagación', 'propagation'],
  ['n', 'micropropagación, cultivo in vitro, cultivo de tejidos', 'micropropagation, in vitro culture, tissue culture'],
  ['n', 'regulador de crecimiento, fitohormona', 'plant growth regulators, phytohormones'],
  ['n', 'fotosíntesis', 'photosynthesis'],
  ['n', 'clorofila', 'chlorophyll'],
  ['n', 'transpiración', 'transpiration'],
  ['n', 'fisiología', 'physiology'],
  ['n', 'fisiología vegetal', 'plant physiology'],
  ['n', 'morfología', 'morphology'],
  ['n', 'anatomía', 'anatomy'],
  ['n', 'fenología', 'phenology'],
  ['n', 'raíz', 'root, roots'],
  ['n', 'hoja', 'leaf, leaves'],
  ['n', 'fruto, fruta', 'fruit, fruits'],
  ['n', 'flor', 'flower, flowers'],
  ['n', 'tallo', 'stem'],
  ['n', 'biomasa', 'biomass'],
  ['n', 'materia seca', 'dry matter'],
  ['n', 'área foliar', 'leaf area'],
  ['n', 'índice de área foliar', 'leaf area index'],
  ['n', 'cosecha', 'harvest'],
  ['n', 'poscosecha', 'postharvest, post-harvest'],
  ['n', 'almacenamiento', 'storage'],
  ['n', 'vida de anaquel, vida útil', 'shelf life'],
  ['n', 'maduración', 'ripening'],
  ['n', 'calidad del fruto', 'fruit quality'],
  ['n', 'sólidos solubles, grados brix', 'soluble solids, total soluble solids'],
  ['n', 'acidez titulable', 'titratable acidity'],
  ['n', 'firmeza', 'firmness'],
  ['n', 'color', 'colour, color'],
  ['n', 'peso del fruto', 'fruit weight'],
  ['n', 'tamaño del fruto', 'fruit size'],
  ['n', 'estrés, estres', 'stress'],
  ['n', 'estrés hídrico', 'water stress, drought stress'],
  ['n', 'sequía', 'drought'],
  ['n', 'estrés salino, salinidad', 'salt stress, salinity'],
  ['n', 'estrés térmico, calor', 'heat stress'],
  ['n', 'helada, frío', 'frost, cold stress'],
  ['n', 'tolerancia', 'tolerance'],
  ['n', 'resistencia', 'resistance'],

  /* ---------- genetics and breeding ---------- */
  ['n', 'recurso genético, recurso fitogenético', 'genetic resources, plant genetic resources'],
  ['n', 'germoplasma', 'germplasm'],
  ['n', 'banco de germoplasma', 'gene banks, germplasm banks'],
  ['n', 'domesticación', 'domestication'],
  ['n', 'variedad, cultivar', 'varieties, cultivars'],
  ['n', 'variedad criolla, raza criolla, variedad local', 'landraces, local varieties'],
  ['n', 'mejoramiento genético, fitomejoramiento', 'plant breeding, genetic improvement, breeding'],
  ['n', 'selección genómica', 'genomic selection'],
  ['n', 'diversidad genética, variabilidad genética', 'genetic diversity, genetic variability, genetic variation'],
  ['n', 'estructura genética', 'genetic structure, population structure'],
  ['n', 'genética de poblaciones', 'population genetics'],
  ['n', 'marcador molecular', 'molecular markers'],
  ['n', 'microsatélite', 'microsatellites, SSR'],
  ['n', 'polimorfismo de nucleótido simple', 'single nucleotide polymorphism, SNP'],
  ['n', 'secuenciación', 'sequencing'],
  ['n', 'genoma', 'genome'],
  ['n', 'genómica', 'genomics'],
  ['n', 'transcriptoma, transcriptómica', 'transcriptome, transcriptomics'],
  ['n', 'expresión génica', 'gene expression'],
  ['n', 'proteómica', 'proteomics'],
  ['n', 'metabolómica', 'metabolomics'],
  ['n', 'filogenia, filogenética', 'phylogeny, phylogenetics'],
  ['n', 'taxonomía', 'taxonomy'],
  ['n', 'biotecnología', 'biotechnology'],
  ['n', 'edición génica, edición genómica', 'gene editing, genome editing, CRISPR'],
  ['n', 'transgénico, organismo genéticamente modificado', 'transgenic, genetically modified organisms, GMO'],

  /* ---------- plant health ---------- */
  ['n', 'plaga', 'pests, insect pests'],
  ['n', 'control biológico', 'biological control, biocontrol'],
  ['n', 'manejo integrado de plagas', 'integrated pest management, IPM'],
  ['n', 'plaguicida, pesticida', 'pesticides'],
  ['n', 'insecticida', 'insecticides'],
  ['n', 'fungicida', 'fungicides'],
  ['n', 'herbicida', 'herbicides'],
  ['n', 'maleza, arvense, mala hierba', 'weeds'],
  ['n', 'enfermedad de plantas, fitopatógeno', 'plant diseases, plant pathogens'],
  ['n', 'patógeno', 'pathogens'],
  ['n', 'hongo', 'fungi'],
  ['n', 'bacteria', 'bacteria'],
  ['n', 'virus', 'viruses, virus'],
  ['n', 'nematodo', 'nematodes'],
  ['n', 'insecto', 'insects'],
  ['n', 'mosca blanca', 'whitefly, whiteflies, Bemisia tabaci'],
  ['n', 'mosca de la fruta', 'fruit flies, Tephritidae'],
  ['n', 'pulgón, áfido', 'aphids'],
  ['n', 'trips', 'thrips'],
  ['n', 'ácaro', 'mites'],
  ['o', 'gusano cogollero', 'fall armyworm, Spodoptera frugiperda'],
  ['n', 'roya', 'rust'],
  ['n', 'antracnosis', 'anthracnose'],
  ['n', 'marchitez', 'wilt'],
  ['n', 'pudrición', 'rot'],
  ['n', 'mildiu', 'downy mildew'],
  ['n', 'cenicilla, oídio', 'powdery mildew'],
  ['n', 'tizón tardío', 'late blight, Phytophthora infestans'],
  ['n', 'resistencia a enfermedades', 'disease resistance'],

  /* ---------- environment ---------- */
  ['n', 'biodiversidad', 'biodiversity'],
  ['n', 'ecología', 'ecology'],
  ['n', 'ecosistema', 'ecosystem, ecosystems'],
  ['n', 'servicio ecosistémico', 'ecosystem services'],
  ['n', 'bosque', 'forest, forests'],
  ['n', 'deforestación', 'deforestation'],
  ['n', 'uso de suelo, uso del suelo, cambio de uso de suelo', 'land use, land-use change'],
  ['n', 'cambio climático', 'climate change'],
  ['n', 'calentamiento global', 'global warming'],
  ['n', 'adaptación', 'adaptation'],
  ['n', 'mitigación', 'mitigation'],
  ['n', 'gas de efecto invernadero', 'greenhouse gases, greenhouse gas emissions'],
  ['n', 'huella de carbono', 'carbon footprint'],
  ['n', 'secuestro de carbono, captura de carbono', 'carbon sequestration'],
  ['n', 'emisión', 'emissions'],
  ['n', 'contaminación', 'pollution, contamination'],
  ['n', 'agua residual', 'wastewater'],
  ['n', 'residuo, desecho', 'waste, residues'],
  ['n', 'residuo agrícola', 'agricultural residues, crop residues'],
  ['n', 'economía circular', 'circular economy'],
  ['n', 'bioeconomía', 'bioeconomy'],
  ['n', 'energía renovable', 'renewable energy'],
  ['n', 'biocombustible', 'biofuels'],
  ['n', 'biogás', 'biogas'],
  ['n', 'modelo de distribución de especies, nicho ecológico', 'species distribution models, ecological niche modeling'],
  ['n', 'sistema de información geográfica', 'geographic information systems, GIS'],
  ['n', 'teledetección, percepción remota', 'remote sensing'],
  ['n', 'imagen satelital', 'satellite imagery'],
  ['n', 'dron, vehículo aéreo no tripulado', 'drones, unmanned aerial vehicles, UAV'],
  ['n', 'inteligencia artificial', 'artificial intelligence'],
  ['n', 'aprendizaje automático', 'machine learning'],
  ['n', 'aprendizaje profundo', 'deep learning'],
  ['n', 'red neuronal', 'neural networks'],
  ['n', 'visión por computadora, visión artificial', 'computer vision'],
  ['n', 'sensor', 'sensors'],
  ['n', 'internet de las cosas', 'internet of things, IoT'],

  /* ---------- food and health ---------- */
  ['n', 'salud', 'health'],
  ['n', 'alimento', 'food, foods'],
  ['n', 'alimento funcional', 'functional foods'],
  ['n', 'inocuidad alimentaria', 'food safety'],
  ['n', 'dieta', 'diet'],
  ['n', 'obesidad', 'obesity'],
  ['n', 'diabetes', 'diabetes, diabetes mellitus'],
  ['n', 'cáncer', 'cancer, neoplasms'],
  ['n', 'hipertensión', 'hypertension'],
  ['n', 'enfermedad', 'disease, diseases'],
  ['n', 'síndrome metabólico', 'metabolic syndrome'],
  ['n', 'inflamación', 'inflammation'],
  ['n', 'actividad antioxidante', 'antioxidant activity, antioxidants'],
  ['n', 'compuesto fenólico, fenol, polifenol', 'phenolic compounds, polyphenols, phenols'],
  ['n', 'flavonoide', 'flavonoids'],
  ['n', 'carotenoide', 'carotenoids'],
  ['n', 'vitamina c, ácido ascórbico', 'vitamin C, ascorbic acid'],
  ['n', 'aceite esencial', 'essential oils'],
  ['n', 'metabolito secundario', 'secondary metabolites'],
  ['n', 'extracto', 'extract, extracts'],
  ['n', 'actividad antimicrobiana', 'antimicrobial activity'],
  ['n', 'actividad antibacteriana', 'antibacterial activity'],
  ['n', 'actividad antifúngica', 'antifungal activity'],
  ['n', 'toxicidad', 'toxicity'],
  ['n', 'citotoxicidad', 'cytotoxicity'],
  ['n', 'etnobotánica', 'ethnobotany'],
  ['n', 'fermentación', 'fermentation'],
  ['n', 'secado, deshidratación', 'drying, dehydration'],
  ['n', 'envasado, empaque', 'packaging'],
  ['n', 'recubrimiento comestible', 'edible coating'],
  ['n', 'aceite', 'oil'],

  /* ---------- animals ---------- */
  ['n', 'ganadería', 'livestock, livestock production'],
  ['n', 'alimentación animal', 'animal feed, animal nutrition'],
  ['n', 'bienestar animal', 'animal welfare'],
  ['n', 'leche', 'milk'],
  ['n', 'carne', 'meat'],
  ['n', 'huevo', 'eggs'],
  ['n', 'acuicultura', 'aquaculture'],
  ['n', 'apicultura', 'beekeeping, apiculture'],
  ['o', 'abeja, abeja melífera', 'bees, honey bee, Apis mellifera'],
  ['o', 'bovino, ganado bovino, vaca', 'cattle, Bos taurus'],
  ['o', 'ovino, oveja', 'sheep, Ovis aries'],
  ['o', 'caprino, cabra', 'goats, Capra hircus'],
  ['o', 'porcino, cerdo', 'pigs, swine, Sus scrofa'],
  ['o', 'ave de corral, pollo, gallina', 'poultry, chickens, broilers, Gallus gallus'],
  ['o', 'pez', 'fish'],
  ['o', 'tilapia', 'tilapia, Oreochromis niloticus'],
  ['o', 'camarón', 'shrimp, Litopenaeus vannamei'],
  ['o', 'ratón', 'mice, mouse'],
  ['o', 'rata', 'rats, rat'],
  ['o', 'humano, ser humano', 'humans'],

  /* ---------- crops and other organisms ---------- */
  ['o', 'maracuyá, maracuya, parchita, fruta de la pasión', 'passion fruit, passionfruit, Passiflora edulis'],
  ['o', 'granadilla', 'sweet granadilla, Passiflora ligularis'],
  ['o', 'gulupa', 'purple passion fruit, gulupa, Passiflora edulis'],
  ['o', 'pasiflora, passiflora', 'Passiflora'],
  ['o', 'chayote', 'chayote, Sechium edule'],
  ['o', 'maíz, maiz', 'maize, corn, Zea mays'],
  ['o', 'teocintle, teosinte', 'teosinte'],
  ['o', 'frijol, fríjol, frejol, poroto', 'common bean, Phaseolus vulgaris'],
  ['o', 'calabaza', 'squash, pumpkin, Cucurbita'],
  ['o', 'trigo', 'wheat, Triticum aestivum'],
  ['o', 'arroz', 'rice, Oryza sativa'],
  ['o', 'cebada', 'barley, Hordeum vulgare'],
  ['o', 'avena', 'oat, oats, Avena sativa'],
  ['o', 'sorgo', 'sorghum, Sorghum bicolor'],
  ['o', 'soya, soja', 'soybean, soya, Glycine max'],
  ['o', 'caña de azúcar', 'sugarcane, Saccharum officinarum'],
  ['o', 'papa, patata', 'potato, Solanum tuberosum'],
  ['o', 'jitomate, tomate rojo, tomate', 'tomato, Solanum lycopersicum'],
  ['o', 'tomate de cáscara, tomate verde, tomatillo, miltomate', 'tomatillo, husk tomato, Physalis philadelphica, Physalis ixocarpa'],
  ['o', 'chile, pimiento, ají', 'chili pepper, pepper, Capsicum annuum'],
  ['o', 'aguacate, palta', 'avocado, Persea americana'],
  ['o', 'mango', 'mango, Mangifera indica'],
  ['o', 'plátano, banano, banana', 'banana, plantain, Musa'],
  ['o', 'café, cafeto', 'coffee, Coffea arabica'],
  ['o', 'cacao', 'cacao, cocoa, Theobroma cacao'],
  ['o', 'vainilla', 'vanilla, Vanilla planifolia'],
  ['o', 'agave, maguey', 'agave, Agave'],
  ['o', 'nopal, tuna', 'prickly pear, nopal, Opuntia ficus-indica'],
  ['o', 'limón, lima', 'lemon, lime, Citrus limon, Citrus aurantifolia'],
  ['o', 'naranja', 'orange, sweet orange, Citrus sinensis'],
  ['o', 'cítrico', 'citrus, Citrus'],
  ['o', 'manzana, manzano', 'apple, Malus domestica'],
  ['o', 'pera', 'pear, Pyrus communis'],
  ['o', 'durazno, melocotón', 'peach, Prunus persica'],
  ['o', 'fresa, frutilla', 'strawberry, Fragaria ananassa'],
  ['o', 'frambuesa', 'raspberry, Rubus idaeus'],
  ['o', 'zarzamora', 'blackberry, Rubus'],
  ['o', 'arándano', 'blueberry, Vaccinium corymbosum'],
  ['o', 'uva, vid', 'grape, grapevine, Vitis vinifera'],
  ['o', 'papaya', 'papaya, Carica papaya'],
  ['o', 'piña', 'pineapple, Ananas comosus'],
  ['o', 'guayaba', 'guava, Psidium guajava'],
  ['o', 'pitahaya, pitaya', 'pitahaya, dragon fruit, Hylocereus, Selenicereus'],
  ['o', 'guanábana', 'soursop, Annona muricata'],
  ['o', 'coco, cocotero', 'coconut, Cocos nucifera'],
  ['o', 'palma de aceite', 'oil palm, Elaeis guineensis'],
  ['o', 'olivo, aceituna', 'olive, Olea europaea'],
  ['o', 'nogal pecanero, nuez pecanera', 'pecan, Carya illinoinensis'],
  ['o', 'almendro, almendra', 'almond, Prunus dulcis'],
  ['o', 'cebolla', 'onion, Allium cepa'],
  ['o', 'ajo', 'garlic, Allium sativum'],
  ['o', 'lechuga', 'lettuce, Lactuca sativa'],
  ['o', 'pepino', 'cucumber, Cucumis sativus'],
  ['o', 'melón', 'melon, Cucumis melo'],
  ['o', 'sandía', 'watermelon, Citrullus lanatus'],
  ['o', 'zanahoria', 'carrot, Daucus carota'],
  ['o', 'brócoli', 'broccoli, Brassica oleracea'],
  ['o', 'col, repollo', 'cabbage, Brassica oleracea'],
  ['o', 'espinaca', 'spinach, Spinacia oleracea'],
  ['o', 'cilantro', 'coriander, cilantro, Coriandrum sativum'],
  ['o', 'amaranto', 'amaranth, Amaranthus'],
  ['o', 'quinua, quinoa', 'quinoa, Chenopodium quinoa'],
  ['o', 'chía', 'chia, Salvia hispanica'],
  ['o', 'girasol', 'sunflower, Helianthus annuus'],
  ['o', 'algodón', 'cotton, Gossypium hirsutum'],
  ['o', 'cacahuate, cacahuete, maní', 'peanut, groundnut, Arachis hypogaea'],
  ['o', 'garbanzo', 'chickpea, Cicer arietinum'],
  ['o', 'lenteja', 'lentil, Lens culinaris'],
  ['o', 'haba', 'faba bean, broad bean, Vicia faba'],
  ['o', 'chícharo, arveja, guisante', 'pea, Pisum sativum'],
  ['o', 'alfalfa', 'alfalfa, lucerne, Medicago sativa'],
  ['o', 'yuca, mandioca', 'cassava, Manihot esculenta'],
  ['o', 'camote, batata', 'sweet potato, Ipomoea batatas'],
  ['o', 'jamaica, flor de jamaica', 'roselle, Hibiscus sabdariffa'],
  ['o', 'estevia, stevia', 'stevia, Stevia rebaudiana'],
  ['o', 'tabaco', 'tobacco, Nicotiana tabacum'],
  ['o', 'arabidopsis', 'Arabidopsis thaliana'],
  ['o', 'pino', 'pine, Pinus'],
  ['o', 'encino, roble', 'oak, Quercus'],
  ['o', 'eucalipto', 'eucalyptus, Eucalyptus'],
  ['o', 'bambú', 'bamboo'],
  ['o', 'cactácea, cactus', 'cacti, Cactaceae'],
  ['o', 'orquídea', 'orchids, Orchidaceae'],
  ['o', 'nochebuena, flor de nochebuena', 'poinsettia, Euphorbia pulcherrima'],
  ['o', 'rosal', 'rose, Rosa'],
  ['o', 'crisantemo', 'chrysanthemum, Chrysanthemum'],
  ['o', 'levadura', 'yeast, Saccharomyces cerevisiae'],
  ['o', 'trichoderma', 'Trichoderma'],
  ['o', 'bacillus', 'Bacillus'],
  ['o', 'rhizobium, rizobio', 'Rhizobium, rhizobia'],
  ['o', 'azospirillum', 'Azospirillum'],
  ['o', 'beauveria bassiana', 'Beauveria bassiana'],
  ['o', 'escherichia coli', 'Escherichia coli, E. coli'],

  /* ---------- places ---------- */
  ['p', 'méxico, mexico', 'Mexico'],
  ['p', 'latinoamérica, américa latina', 'Latin America'],
  ['p', 'centroamérica, américa central', 'Central America'],
  ['p', 'sudamérica, américa del sur', 'South America'],
  ['p', 'brasil', 'Brazil'],
  ['p', 'colombia', 'Colombia'],
  ['p', 'perú', 'Peru'],
  ['p', 'ecuador', 'Ecuador'],
  ['p', 'chile', 'Chile'],
  ['p', 'argentina', 'Argentina'],
  ['p', 'bolivia', 'Bolivia'],
  ['p', 'venezuela', 'Venezuela'],
  ['p', 'guatemala', 'Guatemala'],
  ['p', 'honduras', 'Honduras'],
  ['p', 'nicaragua', 'Nicaragua'],
  ['p', 'costa rica', 'Costa Rica'],
  ['p', 'panamá', 'Panama'],
  ['p', 'cuba', 'Cuba'],
  ['p', 'república dominicana', 'Dominican Republic'],
  ['p', 'uruguay', 'Uruguay'],
  ['p', 'paraguay', 'Paraguay'],
  ['p', 'españa', 'Spain'],
  ['p', 'estados unidos', 'United States, USA'],
  ['p', 'canadá', 'Canada'],
  ['p', 'china', 'China'],
  ['p', 'india', 'India'],
  ['p', 'japón', 'Japan'],
  ['p', 'áfrica', 'Africa'],
  ['p', 'europa', 'Europe'],
  ['p', 'asia', 'Asia'],
  ['p', 'trópico', 'tropics'],
  ['p', 'veracruz', 'Veracruz'],
  ['p', 'oaxaca', 'Oaxaca'],
  ['p', 'chiapas', 'Chiapas'],
  ['p', 'puebla', 'Puebla'],
  ['p', 'jalisco', 'Jalisco'],
  ['p', 'michoacán', 'Michoacan'],
  ['p', 'guerrero', 'Guerrero'],
  ['p', 'yucatán, península de yucatán', 'Yucatan, Yucatan Peninsula'],
  ['p', 'estado de méxico', 'State of Mexico'],
  ['p', 'ciudad de méxico', 'Mexico City'],
  ['p', 'sonora', 'Sonora'],
  ['p', 'sinaloa', 'Sinaloa'],
  ['p', 'chihuahua', 'Chihuahua'],
  ['p', 'tamaulipas', 'Tamaulipas'],
  ['p', 'tabasco', 'Tabasco'],
  ['p', 'morelos', 'Morelos'],
  ['p', 'hidalgo', 'Hidalgo'],
  ['p', 'querétaro', 'Queretaro'],
  ['p', 'guanajuato', 'Guanajuato'],
  ['p', 'san luis potosí', 'San Luis Potosi'],
  ['p', 'zacatecas', 'Zacatecas'],
  ['p', 'durango', 'Durango'],
  ['p', 'nayarit', 'Nayarit'],
  ['p', 'colima', 'Colima'],
  ['p', 'campeche', 'Campeche'],
  ['p', 'quintana roo', 'Quintana Roo'],
  ['p', 'baja california', 'Baja California'],
  ['p', 'nuevo león', 'Nuevo Leon'],
  ['p', 'coahuila', 'Coahuila'],
  ['p', 'aguascalientes', 'Aguascalientes'],
  ['p', 'tlaxcala', 'Tlaxcala'],
];
